upload-img: I:/img/
upload_attachment: I:/attachment/
server:
    port: 8080
spring:
    thymeleaf:
        cache: false
    datasource:
        druid:
            url: jdbc:mysql://localhost:3306/skywordth?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
            username: root
            password: 123456
management:
    endpoints:
        web:
            exposure:
                include: '*'