server:
    port: 9527
    servlet:
        context-path: /
spring:
    datasource:
        name: test
        url: jdbc:mysql://201.0.0.248:3306/ipms?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=UTC
        username: root
        password: Nicai@123
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    activemq:
        broker-url: tcp://201.0.0.248:61616
        pool:
            enabled: true
            max-connections: 10
        user: admin
        password: admin
    redis:
        database: 1
        host: 127.0.0.1
        port: 6379
        password: null
        jedis:
            pool:
                max-idle: 50
                min-idle: 0
                max-active: 1000
                max-wait: -1ms
mybatis:
    mapper-locations: classpath:mapping/*.xml,classpath:mapping/*/*.xml,classpath:mapping/*/*/*.xml
    type-aliases-package: com.keyidea.vsatservice.component.model
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
logging:
    config:classpath: log/logback-spring.xml
    path: D:/home/jwjw
jms:
    pub-sub-domain: false
    activemq:
        user: admin
        password: admin
        broker-url: tcp://201.0.0.248:61616
default:
    userResetPassword: 123321
    redisTimeout: 7200
    systemId: 888167ed335411e9a948
coreUrl: http://201.0.0.251:28080
nmpUrl: http://201.0.0.88:38080
isTest: false